import { z } from 'zod';

export const scoringRulesSchema = z.object({
  pass_yd: z.number().min(-10).max(10),
  pass_td: z.number().min(-10).max(20),
  pass_int: z.number().min(-10).max(0),
  pass_2pt: z.number().min(0).max(10),
  pass_inc: z.number().min(-5).max(5),
  pass_att: z.number().min(-5).max(5),
  rush_yd: z.number().min(-10).max(10),
  rush_td: z.number().min(0).max(20),
  rush_att: z.number().min(-5).max(5),
  rush_2pt: z.number().min(0).max(10),
  rec: z.number().min(0).max(5),
  rec_yd: z.number().min(-10).max(10),
  rec_td: z.number().min(0).max(20),
  rec_2pt: z.number().min(0).max(10),
  rec_target: z.number().min(-5).max(5),
  fg_made_0_39: z.number().min(0).max(10),
  fg_made_40_49: z.number().min(0).max(10),
  fg_made_50_59: z.number().min(0).max(10),
  fg_made_60_plus: z.number().min(0).max(15),
  fg_missed: z.number().min(-10).max(0),
  xp_made: z.number().min(0).max(5),
  xp_missed: z.number().min(-5).max(0),
  dst_sack: z.number().min(0).max(10),
  dst_int: z.number().min(0).max(10),
  dst_fumble_rec: z.number().min(0).max(10),
  dst_safety: z.number().min(0).max(10),
  dst_td: z.number().min(0).max(20),
  dst_blk: z.number().min(0).max(10),
  dst_pts_allowed_0: z.number().min(0).max(20),
  dst_pts_allowed_1_6: z.number().min(0).max(20),
  dst_pts_allowed_7_13: z.number().min(-10).max(20),
  dst_pts_allowed_14_20: z.number().min(-10).max(20),
  dst_pts_allowed_21_27: z.number().min(-10).max(10),
  dst_pts_allowed_28_34: z.number().min(-10).max(5),
  dst_pts_allowed_35_plus: z.number().min(-10).max(0),
  dst_yds_allowed_0_99: z.number().min(-10).max(10),
  dst_yds_allowed_100_199: z.number().min(-10).max(10),
  dst_yds_allowed_200_299: z.number().min(-10).max(10),
  dst_yds_allowed_300_399: z.number().min(-10).max(10),
  dst_yds_allowed_400_plus: z.number().min(-10).max(10),
  fumble_lost: z.number().min(-10).max(0),
  fumble: z.number().min(-10).max(0),
  return_td: z.number().min(0).max(20),
});

export const scoringBonusSchema = z.object({
  stat: z.string(),
  threshold: z.number().min(1),
  bonus: z.number().min(0.25).max(50),
  label: z.string().optional(),
});

export const scoringConfigSchema = z.object({
  rules: scoringRulesSchema,
  bonuses: z.array(scoringBonusSchema),
  pprValue: z.number().min(0).max(2),
});
